superlists/accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
        url(r'^login$', 'accounts.views.login', name='login'),
        url(r'^logout$', 'accounts.views.logout', name='logout')
    )

superlists/lists/urls.py
from django.conf.urls import url

from . import views

app_name = 'lists'
urlpatterns = [
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^new$', views.new_list, name='new_list')
    # url(r'^admin/', admin.site.urls),
]

superlists/superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from lists import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls'))
    # url(r'^admin/', admin.site.urls),
]

superlists/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

# Create your models here.
    
class ListUserManager(BaseUserManager):
    def create_user(self, email):
        ListUser.objects.create(email=email)

    def create_superuser(self, email, password):
        self.create_user(email)

class ListUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(primary_key=True)
    USERNAME_FIELD = 'email'

    objects = ListUserManager()

    @property
    def is_staff(self):
        return self.email == 'myemail@example.com'
    
    @property
    def is_active(self):
        return True

superlists/lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, null=True)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

superlists/lists/forms.py
from django import forms

from lists.models import Item

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
                }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except forms.ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

superlists/accounts/views.py
import sys
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import redirect

def login(request):
    print('login view', file=sys.stderr)
    user = authenticate(assertion=request.POST['assertion'])
    if user is not None:
        auth_login(request, user)
    return redirect('/')

def logout(request):
    auth_logout(request)
    return redirect('/')

superlists/lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.exceptions import ValidationError

from .models import Item, List

from .forms import ItemForm, ExistingListItemForm

# Create your views here.
def home_page(request):
    return render(request, 'lists/home.html', {'form': ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'lists/list.html', {
        'list': list_,
        'form': form
        })

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'lists/home.html', {'form': form})

superlists/lists/templates/base.html
<html>
    <head>
        <title>To-Do lists</title>

        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/base.css">
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                {% if user.email %}
                    <p>Logged in as {{user.email}}</p>
                    <p>
                        <a href="{% url 'logout' %}" id="logout">Sign Out</a>
                    </p>
                {% else %}
                    <a href="#" id="login">Sign In</a>
                {% endif %}
                <p>User: {{user}}</p>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>
                            {% block header_text %}{% endblock header_text %}
                        </h1>
                        <form
                            method="post"
                            action="{% block form_action %}{% endblock form_action %}">
                            {{form.text}}
                            {% csrf_token %}

                            {% if form.errors %}
                                <div class="form-group has-error">
                                    <span class="help-block">{{form.text.errors}}</span>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock table %}
                </div>
            </div>

        </div>

    <script src="/static/tests/jquery.min.js"></script>
    <script src="/static/js/list.js"></script>
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="/static/list.js"></script>
<script src="https://login.persona.org/include.js"></script>
<script>
    $(document).ready(function() {
        var loginLink = document.getElementById('login');
        if (loginLink) {
            loginLink.onclick = function() { navigator.id.request(); };
        }
        var logoutLink = document.getElementById('logout');
        if (logoutLink) {
            logoutLink.onclick = function() { navigator.id.logout(); };
        }
        var currentUser = '{{ user.email }}' || null;
        var csrf_token = '{{ csrf_token }}';
        console.log(currentUser);
        navigator.id.watch({
            loggedInUser: currentUser,
            onlogin: function(assertion) {
                $.post('/accounts/login', {assertion: assertion, csrfmiddlewaretoken: csrf_token})
            .done(function() { window.location.reload(); })
            .fail(function() { navigator.id.logout();});
        },
        onlogout: function() {
            $.post('/accounts/logout')
            .always(function() { window.location.reload(); });
        }
        });
    });
</script>
    </body>
</html>

superlists/lists/templates/lists/home.html
{% extends "base.html" %}
{% block header_text %}Start a New To-Do lists{% endblock header_text %}

{% block form_action %}{% url 'new_list' %}{% endblock form_action %}

superlists/lists/templates/lists/list.html
{% extends "base.html" %}
{% block header_text %}Your To-Do lists{% endblock header_text %}

{% block form_action %}/lists/{{list.id}}/{% endblock form_action %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{forloop.counter}}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock table %}